# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  url_shortener:
    build: .
      # context: .
      # dockerfile: Dockerfile.url_shortener
    container_name: url_shortener_service
    depends_on:
      - redis
      - auth_service
    environment:
      - REDIS_HOST=redis
      - AUTH_SERVICE_URL=http://auth-service-service:8001
    command: python3 backend/api/url-shortener-service/index.py
    ports:
      - "8000:8000"

  auth_service:
    build: .
      # context: .
      # dockerfile: Dockerfile.auth_service
    container_name: auth_service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: python3 backend/api/auth-service/auth_service.py
    ports:
      - "8001:8001"

volumes:
  redis_data:

